name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    uses: ./.github/workflows/run-tests.yml

  lint:
    uses: ./.github/workflows/run-linters.yml

  push:
    needs: [test, lint]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/push.yml
